label_columns:
  - class: int #[1, 2, 3]  # Specify allowed labels for the "class" column


columns:
  - class : category
  - Time_step : int
  - Local_feature_1 : float
  - Local_feature_2 : float
  - Local_feature_3 : float
  - Local_feature_4 : float
  - Local_feature_5 : float
  - Local_feature_6 : float
  - Local_feature_7 : float
  - Local_feature_8 : float
  - Local_feature_9 : float
  - Local_feature_10 : float
  - Local_feature_11 : float
  - Local_feature_12 : float
  - Local_feature_13 : float
  - Local_feature_14 : float
  - Local_feature_15 : float
  - Local_feature_16 : float
  - Local_feature_17 : float
  - Local_feature_18 : float
  - Local_feature_19 : float
  - Local_feature_20 : float
  - Local_feature_21 : float
  - Local_feature_22 : float
  - Local_feature_23 : float
  - Local_feature_24 : float
  - Local_feature_25 : float
  - Local_feature_26 : float
  - Local_feature_27 : float
  - Local_feature_28 : float
  - Local_feature_29 : float
  - Local_feature_30 : float
  - Local_feature_31 : float
  - Local_feature_32 : float
  - Local_feature_33 : float
  - Local_feature_34 : float
  - Local_feature_35 : float
  - Local_feature_36 : float
  - Local_feature_37 : float
  - Local_feature_38 : float
  - Local_feature_39 : float
  - Local_feature_40 : float
  - Local_feature_41 : float
  - Local_feature_42 : float
  - Local_feature_43 : float
  - Local_feature_44 : float
  - Local_feature_45 : float
  - Local_feature_46 : float
  - Local_feature_47 : float
  - Local_feature_48 : float
  - Local_feature_49 : float
  - Local_feature_50 : float
  - Local_feature_51 : float
  - Local_feature_52 : float
  - Local_feature_53 : float
  - Local_feature_54 : float
  - Local_feature_55 : float
  - Local_feature_56 : float
  - Local_feature_57 : float
  - Local_feature_58 : float
  - Local_feature_59 : float
  - Local_feature_60 : float
  - Local_feature_61 : float
  - Local_feature_62 : float
  - Local_feature_63 : float
  - Local_feature_64 : float
  - Local_feature_65 : float
  - Local_feature_66 : float
  - Local_feature_67 : float
  - Local_feature_68 : float
  - Local_feature_69 : float
  - Local_feature_70 : float
  - Local_feature_71 : float
  - Local_feature_72 : float
  - Local_feature_73 : float
  - Local_feature_74 : float
  - Local_feature_75 : float
  - Local_feature_76 : float
  - Local_feature_77 : float
  - Local_feature_78 : float
  - Local_feature_79 : float
  - Local_feature_80 : float
  - Local_feature_81 : float
  - Local_feature_82 : float
  - Local_feature_83 : float
  - Local_feature_84 : float
  - Local_feature_85 : float
  - Local_feature_86 : float
  - Local_feature_87 : float
  - Local_feature_88 : float
  - Local_feature_89 : float
  - Local_feature_90 : float
  - Local_feature_91 : float
  - Local_feature_92 : float
  - Local_feature_93 : float
  - Aggregate_feature_1 : float
  - Aggregate_feature_2 : float
  - Aggregate_feature_3 : float
  - Aggregate_feature_4 : float
  - Aggregate_feature_5 : float
  - Aggregate_feature_6 : float
  - Aggregate_feature_7 : float
  - Aggregate_feature_8 : float
  - Aggregate_feature_9 : float
  - Aggregate_feature_10 : float
  - Aggregate_feature_11 : float
  - Aggregate_feature_12 : float
  - Aggregate_feature_13 : float
  - Aggregate_feature_14 : float
  - Aggregate_feature_15 : float
  - Aggregate_feature_16 : float
  - Aggregate_feature_17 : float
  - Aggregate_feature_18 : float
  - Aggregate_feature_19 : float
  - Aggregate_feature_20 : float
  - Aggregate_feature_21 : float
  - Aggregate_feature_22 : float
  - Aggregate_feature_23 : float
  - Aggregate_feature_24 : float
  - Aggregate_feature_25 : float
  - Aggregate_feature_26 : float
  - Aggregate_feature_27 : float
  - Aggregate_feature_28 : float
  - Aggregate_feature_29 : float
  - Aggregate_feature_30 : float
  - Aggregate_feature_31 : float
  - Aggregate_feature_32 : float
  - Aggregate_feature_33 : float
  - Aggregate_feature_34 : float
  - Aggregate_feature_35 : float
  - Aggregate_feature_36 : float
  - Aggregate_feature_37 : float
  - Aggregate_feature_38 : float
  - Aggregate_feature_39 : float
  - Aggregate_feature_40 : float
  - Aggregate_feature_41 : float
  - Aggregate_feature_42 : float
  - Aggregate_feature_43 : float
  - Aggregate_feature_44 : float
  - Aggregate_feature_45 : float
  - Aggregate_feature_46 : float
  - Aggregate_feature_47 : float
  - Aggregate_feature_48 : float
  - Aggregate_feature_49 : float
  - Aggregate_feature_50 : float
  - Aggregate_feature_51 : float
  - Aggregate_feature_52 : float
  - Aggregate_feature_53 : float
  - Aggregate_feature_54 : float
  - Aggregate_feature_55 : float
  - Aggregate_feature_56 : float
  - Aggregate_feature_57 : float
  - Aggregate_feature_58 : float
  - Aggregate_feature_59 : float
  - Aggregate_feature_60 : float
  - Aggregate_feature_61 : float
  - Aggregate_feature_62 : float
  - Aggregate_feature_63 : float
  - Aggregate_feature_64 : float
  - Aggregate_feature_65 : float
  - Aggregate_feature_66 : float
  - Aggregate_feature_67 : float
  - Aggregate_feature_68 : float
  - Aggregate_feature_69 : float
  - Aggregate_feature_70 : float
  - Aggregate_feature_71 : float
  - Aggregate_feature_72 : float
  

numerical_columns:
  - Time_step
  - Local_feature_1
  - Local_feature_2
  - Local_feature_3
  - Local_feature_4
  - Local_feature_5
  - Local_feature_6
  - Local_feature_7
  - Local_feature_8
  - Local_feature_9
  - Local_feature_10
  - Local_feature_11
  - Local_feature_12
  - Local_feature_13
  - Local_feature_14
  - Local_feature_15
  - Local_feature_16
  - Local_feature_17
  - Local_feature_18
  - Local_feature_19
  - Local_feature_20
  - Local_feature_21
  - Local_feature_22
  - Local_feature_23
  - Local_feature_24
  - Local_feature_25
  - Local_feature_26
  - Local_feature_27
  - Local_feature_28
  - Local_feature_29
  - Local_feature_30
  - Local_feature_31
  - Local_feature_32
  - Local_feature_33
  - Local_feature_34
  - Local_feature_35
  - Local_feature_36
  - Local_feature_37
  - Local_feature_38
  - Local_feature_39
  - Local_feature_40
  - Local_feature_41
  - Local_feature_42
  - Local_feature_43
  - Local_feature_44
  - Local_feature_45
  - Local_feature_46
  - Local_feature_47
  - Local_feature_48
  - Local_feature_49
  - Local_feature_50
  - Local_feature_51
  - Local_feature_52
  - Local_feature_53
  - Local_feature_54
  - Local_feature_55
  - Local_feature_56
  - Local_feature_57
  - Local_feature_58
  - Local_feature_59
  - Local_feature_60
  - Local_feature_61
  - Local_feature_62
  - Local_feature_63
  - Local_feature_64
  - Local_feature_65
  - Local_feature_66
  - Local_feature_67
  - Local_feature_68
  - Local_feature_69
  - Local_feature_70
  - Local_feature_71
  - Local_feature_72
  - Local_feature_73
  - Local_feature_74
  - Local_feature_75
  - Local_feature_76
  - Local_feature_77
  - Local_feature_78
  - Local_feature_79
  - Local_feature_80
  - Local_feature_81
  - Local_feature_82
  - Local_feature_83
  - Local_feature_84
  - Local_feature_85
  - Local_feature_86
  - Local_feature_87
  - Local_feature_88
  - Local_feature_89
  - Local_feature_90
  - Local_feature_91
  - Local_feature_92
  - Local_feature_93
  - Aggregate_feature_1
  - Aggregate_feature_2
  - Aggregate_feature_3
  - Aggregate_feature_4
  - Aggregate_feature_5
  - Aggregate_feature_6
  - Aggregate_feature_7
  - Aggregate_feature_8
  - Aggregate_feature_9
  - Aggregate_feature_10
  - Aggregate_feature_11
  - Aggregate_feature_12
  - Aggregate_feature_13
  - Aggregate_feature_14
  - Aggregate_feature_15
  - Aggregate_feature_16
  - Aggregate_feature_17
  - Aggregate_feature_18
  - Aggregate_feature_19
  - Aggregate_feature_20
  - Aggregate_feature_21
  - Aggregate_feature_22
  - Aggregate_feature_23
  - Aggregate_feature_24
  - Aggregate_feature_25
  - Aggregate_feature_26
  - Aggregate_feature_27
  - Aggregate_feature_28
  - Aggregate_feature_29
  - Aggregate_feature_30
  - Aggregate_feature_31
  - Aggregate_feature_32
  - Aggregate_feature_33
  - Aggregate_feature_34
  - Aggregate_feature_35
  - Aggregate_feature_36
  - Aggregate_feature_37
  - Aggregate_feature_38
  - Aggregate_feature_39
  - Aggregate_feature_40
  - Aggregate_feature_41
  - Aggregate_feature_42
  - Aggregate_feature_43
  - Aggregate_feature_44
  - Aggregate_feature_45
  - Aggregate_feature_46
  - Aggregate_feature_47
  - Aggregate_feature_48
  - Aggregate_feature_49
  - Aggregate_feature_50
  - Aggregate_feature_51
  - Aggregate_feature_52
  - Aggregate_feature_53
  - Aggregate_feature_54
  - Aggregate_feature_55
  - Aggregate_feature_56
  - Aggregate_feature_57
  - Aggregate_feature_58
  - Aggregate_feature_59
  - Aggregate_feature_60
  - Aggregate_feature_61
  - Aggregate_feature_62
  - Aggregate_feature_63
  - Aggregate_feature_64
  - Aggregate_feature_65
  - Aggregate_feature_66
  - Aggregate_feature_67
  - Aggregate_feature_68
  - Aggregate_feature_69
  - Aggregate_feature_70
  - Aggregate_feature_71
  - Aggregate_feature_72


label_columns:
  - class: [1, 2, "unknown"]  # Specify allowed labels for the "class" column


drop_columns:
  - txId